Repository DimoDimchev/Trivial, pull requests merged in 2021-10, with the labels that each got.

#58 Implement Reference Microservice
  reference/.gitignore
  reference/reference/__init__.py
  reference/reference/blueprints/crypto.py
  reference/reference/blueprints/stocks.py
  reference/reference/utils/api_spec.py
  reference/reference/utils/extensions.py
  reference/reference/utils/swagger.py
  reference/requirements.txt
Labels: microservices

#70 Added comments for nordigen.py file in assets
  assets/utils/nordigen.py
Labels: microservices

#68 Implement logic for Yodlee into the Assets microservice
  assets/requirements.txt
  assets/src/blueprints/balances.py
  assets/src/blueprints/transactions.py
  assets/utils/yodlee.py
Labels: microservices

#80 Add edit user functionality
  account/.gitignore
  account/README.md
  account/account/account/__init__.py
  account/account/account/asgi.py
  account/account/account/settings.py
  account/account/account/urls.py
  account/account/account/wsgi.py
  account/account/authentication/__init__.py
  account/account/authentication/admin.py
  account/account/authentication/apps.py
  account/account/authentication/common_shared/__init__.py
  account/account/authentication/common_shared/utils.py
  account/account/authentication/models.py
  account/account/authentication/serializers.py
  account/account/authentication/tests.py
  account/account/authentication/urls.py
  account/account/authentication/views/__init__.py
  account/account/authentication/views/delete_profile_view.py
  account/account/authentication/views/edit_user_profile_view.py
  account/account/authentication/views/get_and_create_view.py
  account/account/manage.py
  account/account/requirements.txt
  client/src/components/DashboardPage.js
  server/account/authentication/models.py
  server/account/authentication/serializers.py
  server/account/authentication/views/edit_user_profile_view.py
  server/account/authentication/views/get_and_create_view.py
Labels: enhancement, microservices

#85 Origin/niki/issue/81/field encryption
  account/account/account/settings.py
  account/account/authentication/common_shared/utils.py
  account/account/authentication/models.py
  account/account/authentication/serializers.py
  account/account/authentication/urls.py
  account/account/authentication/views/delete_profile_view.py
  account/account/authentication/views/edit_user_profile_view.py
  account/account/authentication/views/get_and_create_view.py
  account/account/requirements.txt
Labels: microservices, encryption

#105 Added tests, and minor improvements to Account
  account/account/account/settings.py
  account/account/authentication/tests.py
  account/account/authentication/tests/__init__.py
  account/account/authentication/tests/tests_views.py
  account/account/authentication/urls.py
  account/account/authentication/views/get_put_delete_view.py
  account/account/requirements.txt
  client/src/components/DashboardPage.js
Labels: enhancement, tests, microservices

#116 Add logic for Custom Assets API to the holdings endpoint in Assets
  assets/src/blueprints/balances.py
  assets/src/blueprints/holdings.py
  assets/src/blueprints/transactions.py
  assets/utils/custom_assets_api.py
  assets/utils/yodlee_api.py
Labels: enhancement, microservices

#151 fixed docker-compose up bug for client
  client/package.json
Labels: bug

#148 Change client transactions logic to work with portfolio
  assets_v2/assets/utils/coinbase_api.py
  client/src/components/Other/BalanceComponent.js
  client/src/components/Other/BalancesContainerComponent.js
  client/src/components/Other/HoldingComponent.js
  client/src/components/Other/HoldingsContainerComponent.js
  client/src/components/Pages/DashboardPage.js
  client/src/styles/dashboard.css
  client/src/utils/portfolio.js
Labels: client
