Repository DimoDimchev/Trivial, pull requests merged in 2021-11, with the labels that each got.

#153 Change the way responses are stored in the .csv file
  campaign/backend/backend/blueprints/api.py
Labels: enhancement

#154 Add functionality to store nordigen reqisitions and register Yodlee login name
  account/account/account/settings.py
  account/account/authentication/admin.py
  account/account/authentication/apps.py
  account/account/authentication/common_shared/utils.py
  account/account/authentication/migrations/0001_initial.py
  account/account/authentication/models.py
  account/account/authentication/serializers.py
  account/account/authentication/urls.py
  account/account/authentication/views/create_delete_nordigen_requisition.py
  account/account/authentication/views/get_put_delete_view.py
  account/account/requirements.txt
  client/yarn.lock
Labels: microservices

#172 Change docker images python/node from latest version to specific version
  account/account/Dockerfile
  assets_v2/Dockerfile
  client/Dockerfile
  client/package.json
  custom_assets/Dockerfile
  reference/Dockerfile
Labels: enhancement

#174 Add logic for unselecting quiz answers
  campaign/client/src/components/QuizComponent.js
Labels: bugfix

#175 Add endpoint for yodlee token
  account/account/authentication/common_shared/utils.py
  account/account/authentication/serializers.py
  account/account/authentication/urls.py
  account/account/authentication/views/get_put_delete_view.py
  account/account/authentication/views/yodlee_token.py
Labels: microservices

#179 Migrate database
  server/account/account/account/settings.py
  server/account/account/authentication/migrations/0001_initial.py
  server/account/account/authentication/models.py
Labels: enhancement

#183 Fix tests
  server/account/account/authentication/migrations/0002_remove_userprofile_coinbase_api_pass.py
  server/account/account/authentication/models.py
  server/account/account/authentication/tests/tests_views.py
Labels: tests, microservices

#184 Update portfolio and assets to work with new account changes
  server/assets_v2/assets/blueprints/api.py
  server/assets_v2/assets/utils/nordigen.py
  server/portfolio/portfolio/blueprints/api.py
  server/portfolio/requirements.txt
Labels: microservices

#185 Add logic for linking accounts using Yodlee
  client/public/index.html
  client/src/components/Pages/ProfilePage.js
  client/src/utils/account.js
  server/assets_v2/assets/utils/yodlee_api.py
  server/portfolio/portfolio/blueprints/api.py
Labels: client

#188 Added endpoint for account to retrieve banks from nordigen
  server/account/account/authentication/urls.py
  server/account/account/authentication/views/nordigen_banks.py
Labels: microservices

#190 Fix bug with get nordigen banks and create new requisitions
  server/account/account/authentication/migrations/0001_initial.py
  server/account/account/authentication/migrations/0002_remove_userprofile_coinbase_api_pass.py
  server/account/account/authentication/models.py
  server/account/account/authentication/views/create_delete_nordigen_requisition.py
Labels: bug, microservices

#191 Fix bugs on landing page
  campaign/client/public/android-chrome-192x192.png
  campaign/client/public/android-chrome-512x512.png
  campaign/client/public/apple-touch-icon.png
  campaign/client/public/favicon-16x16.png
  campaign/client/public/favicon-32x32.png
  campaign/client/public/favicon.ico
  campaign/client/public/index.html
  campaign/client/public/site.webmanifest
  campaign/client/src/App.css
  campaign/client/src/components/CongratulateComponent.js
  campaign/client/src/components/EarlyAccessForm.js
  campaign/client/src/components/HeaderComponent.js
  campaign/client/src/components/LandingPage.js
  campaign/client/src/components/QuizComponent.js
  campaign/client/src/components/TopBodyComponent.js
  campaign/client/src/images/favicon.png
  campaign/client/src/images/favicon.svg
  campaign/client/src/images/image1.jpg
  campaign/client/src/images/image1.png
  campaign/client/src/images/image1.svg
  campaign/client/src/images/image2.jpg
  campaign/client/src/images/image2.png
  campaign/client/src/images/image2.svg
  campaign/client/src/images/image3.jpg
  campaign/client/src/images/image3.png
  campaign/client/src/images/image3.svg
  campaign/client/src/images/logo.png
Labels: bug, enhancement, landing page

#196 Changed nordigen error response in account
  server/account/account/authentication/views/create_delete_nordigen_requisition.py
Labels: enhancement, microservices

#192 Add frontend logic for linking bank account via Nordigen
  client/package.json
  client/src/App.js
  client/src/components/Other/BanksContainer.js
  client/src/components/Other/DropDown.js
  client/src/components/Pages/ProfilePage.js
  client/src/utils/nordigen.js
Labels: enhancement, client

#198 Add frontend logic for adding custom assets
  client/src/components/Other/AssetsDropDownList.js
  client/src/components/Other/CountriesDropDownList.js
  client/src/components/Pages/ProfilePage.js
  client/src/utils/nordigen.js
  client/src/utils/portfolio.js
  server/assets_v2/assets/utils/custom_assets_api.py
  server/portfolio/portfolio/blueprints/api.py
  server/portfolio/portfolio/utils/custom_assets.py
Labels: enhancement, client

#193 Iphone button and motorola g5
  campaign/client/public/Logo.svg
  campaign/client/public/index.html
  campaign/client/src/App.css
  campaign/client/src/components/EarlyAccessForm.js
  campaign/client/src/components/QuizComponent.js
  campaign/client/src/components/TopBodyComponent.js
Labels: bug, landing page

#201 Fixed duplicate asset bug in CustomAssets
  server/custom_assets/api/serializers.py
  server/custom_assets/api/utils/serializer_validators.py
Labels: bug, microservices

#206 Add logic for separating Portfolio output into groups, based on source
  client/src/components/Other/BalanceComponent.js
  client/src/components/Other/BalancesContainerComponent.js
  client/src/components/Other/GroupComponent.js
  client/src/components/Other/GroupsContainerComponent.js
  client/src/components/Other/HoldingComponent.js
  client/src/components/Other/HoldingsContainerComponent.js
  client/src/components/Pages/DashboardPage.js
  server/assets_v2/assets/utils/yodlee_api.py
  server/portfolio/portfolio/blueprints/api.py
  server/portfolio/portfolio/utils/format.py
Labels: client

#205 Display value of assets converted to base currency
  server/portfolio/portfolio/blueprints/api.py
  server/portfolio/portfolio/utils/reference.py
  server/reference/reference/blueprints/currencies.py
Labels: microservices

#209 Display total balance per source and account balances in base currency
  client/src/components/Other/GroupComponent.js
  client/src/components/Other/GroupsContainerComponent.js
  client/src/components/Other/HoldingComponent.js
  client/src/components/Pages/DashboardPage.js
  server/portfolio/portfolio/utils/format.py
Labels: client

#211 Add option to change base currency in the profile page in Client
  client/src/components/Other/BaseCurrencyDropDownList.js
  client/src/components/Pages/ProfilePage.js
Labels: client

#213 Added database to portfolio for caching user assets
  server/portfolio/portfolio/blueprints/api.py
  server/portfolio/portfolio/utils/cache_assets.py
  server/portfolio/portfolio/utils/reference.py
  server/portfolio/requirements.txt
Labels: microservices

#215 Fix bug in portfolio for assets that have a missing base_currency field
  server/portfolio/portfolio/utils/format.py
Labels: bugfix

#218 Render the account type for each account in Client
  client/src/components/Other/GroupComponent.js
  client/src/components/Other/GroupsContainerComponent.js
  server/assets_v2/assets/utils/nordigen.py
  server/assets_v2/assets/utils/yodlee_api.py
Labels: enhancement, client

#219 Changed transactions currency to base currency
  server/portfolio/portfolio/blueprints/api.py
  server/portfolio/portfolio/utils/reference.py
Labels: microservices

#223 Added base currency for stocks
  server/portfolio/portfolio/utils/reference.py
Labels: microservices

#225 Show just the assets if sources related to yodlee have holdings and have only one account
  client/src/components/Other/BaseCurrencyDropDownList.js
  client/src/components/Other/GroupsContainerComponent.js
  client/src/components/Other/HoldingComponent.js
Labels: bugfix

#228 Monitor service with 2FA authentication
  server/monitor/.gitignore
  server/monitor/README.md
  server/monitor/manage.py
  server/monitor/monitor/__init__.py
  server/monitor/monitor/asgi.py
  server/monitor/monitor/settings.py
  server/monitor/monitor/urls.py
  server/monitor/monitor/wsgi.py
  server/monitor/monitor_app/__init__.py
  server/monitor/monitor_app/admin.py
  server/monitor/monitor_app/apps.py
  server/monitor/monitor_app/forms.py
  server/monitor/monitor_app/migrations/__init__.py
  server/monitor/monitor_app/models.py
  server/monitor/monitor_app/tests.py
  server/monitor/monitor_app/urls.py
  server/monitor/monitor_app/utils.py
  server/monitor/monitor_app/views.py
  server/monitor/requirements.txt
  server/monitor/templates/barcode.html
  server/monitor/templates/index.html
  server/monitor/templates/register.html
  server/monitor/templates/registration/login.html
Labels: microservices

#227 Fixed bug when there are no transactions
  server/portfolio/portfolio/utils/reference.py
Labels: bug

#232 Monitor bugfix
  server/monitor/monitor_app/forms.py
  server/monitor/monitor_app/urls.py
  server/monitor/monitor_app/utils.py
  server/monitor/monitor_app/views.py
  server/monitor/templates/barcode.html
  server/monitor/templates/registration/login.html
Labels: bug

#231 Refactored database connections in monitor and add connection to portfolio database
  server/monitor/monitor_app/utils.py
Labels: microservices

#234 Changed assets caching format
  server/monitor/monitor_app/utils.py
  server/portfolio/portfolio/blueprints/api.py
  server/portfolio/portfolio/utils/cache_assets.py
  server/portfolio/portfolio/utils/format.py
  server/portfolio/portfolio/utils/reference.py
Labels: enhancement

#236 Add the total balance to the dashboard
  client/src/components/Other/GroupComponent.js
  client/src/components/Other/GroupsContainerComponent.js
  client/src/components/Pages/DashboardPage.js
  server/portfolio/portfolio/blueprints/api.py
  server/portfolio/portfolio/utils/format.py
Labels: enhancement

#240 Add functionality for getting all/ recent transactions
  client/src/components/Other/GroupsContainerComponent.js
  client/src/components/Other/HoldingComponent.js
  client/src/components/Other/RecentTransactionsContainerComponent.js
  client/src/components/Pages/DashboardPage.js
  client/src/utils/portfolio.js
  server/assets_v2/assets/blueprints/api.py
  server/assets_v2/assets/utils/coinbase_api.py
  server/assets_v2/assets/utils/nordigen.py
  server/assets_v2/assets/utils/yodlee_api.py
  server/assets_v2/requirements.txt
  server/portfolio/portfolio/blueprints/api.py
  server/portfolio/portfolio/utils/assets.py
  server/portfolio/portfolio/utils/reference.py
Labels: enhancement

#242 response time optimisations for get_balances in assets microservice
  server/assets_v2/assets/blueprints/api.py
  server/assets_v2/assets/utils/measure_time.py
  server/assets_v2/assets/utils/nordigen.py
  server/assets_v2/assets/utils/yodlee_api.py
Labels: microservices

#244 Maked response time optimistaions in portfolio/assets
  server/portfolio/portfolio/blueprints/api.py
  server/portfolio/portfolio/utils/format.py
  server/portfolio/portfolio/utils/reference.py
Labels: microservices

#245 Implement design to front end client
  .gitignore
  client/.gitignore
  client/package.json
  client/src/components/Other/ChartComponent.js
  client/src/components/Other/GroupsContainerComponent.js
  client/src/components/Other/HeaderComponent.js
  client/src/components/Other/LoaderComponent.js
  client/src/components/Other/SubHeaderComponent.js
  client/src/components/Pages/DashboardPage.js
  client/src/components/Pages/LandingPage.js
  client/src/images/Notification.svg
  client/src/images/Services.svg
  client/src/images/Vector_down.svg
  client/src/images/double-arrow.svg
  client/src/images/fake_graph.png
  client/src/images/fake_notifications.png
  client/src/images/logo.svg
  client/src/images/messages-2.svg
  client/src/images/profile_Img.svg
  client/src/styles/chart_component.scss
  client/src/styles/dashboard.css
  client/src/styles/dashboard.scss
  client/src/styles/header.scss
  client/src/styles/loader.scss
  client/src/styles/main_content.scss
  client/src/styles/subheader.scss
  client/yarn.lock
Labels: enhancement, client

#252 Frontend currency button active
  client/src/components/Other/BaseCurrencyDropDownList.js
  client/src/components/Other/GroupsContainerComponent.js
  client/src/components/Other/HeaderComponent.js
  client/src/components/Pages/DashboardPage.js
  client/src/components/Pages/ProfilePage.js
  client/src/styles/chart_component.scss
  client/src/styles/dashboard.scss
  client/src/styles/header.scss
  client/src/styles/main_content.scss
Labels: client

#250 Add logic for getting historical balances
  client/src/utils/portfolio.js
  server/portfolio/portfolio/blueprints/api.py
  server/portfolio/portfolio/utils/format.py
Labels: enhancement

#255 Translate frontend logic into the design
  client/package.json
  client/src/components/Other/BaseCurrencyDropDownList.js
  client/src/components/Other/HeaderComponent.js
  client/src/components/Other/RecentTransactionsContainerComponent.js
  client/src/components/Other/SubHeaderComponent.js
  client/src/components/Pages/DashboardPage.js
Labels: enhancement, client

#259 Extend routing in Client
  client/src/App.js
  client/src/components/Other/HeaderComponent.js
  client/src/components/Pages/AdvicePage.js
  client/src/components/Pages/CashflowPage.js
  client/src/components/Pages/DashboardPage.js
  client/src/components/Pages/PortfolioPage.js
Labels: enhancement, client

#261 Style the source groups in Client
  client/src/components/Other/GroupComponent.js
  client/src/components/Other/GroupsContainerComponent.js
  client/src/components/Other/HoldingComponent.js
  client/src/styles/dashboard.scss
Labels: enhancement, client

#262 Added functionality to add new source button
  client/src/components/Other/AddCryptoSource.js
  client/src/components/Other/AddNewSourceComponent.js
  client/src/components/Other/AddNewSourceMenu.js
  client/src/components/Other/AddNewSourceModal.js
  client/src/components/Other/AddYodleeComponent.js
  client/src/components/Other/BanksContainer.js
  client/src/components/Other/CountriesDropDownList.js
  client/src/components/Pages/DashboardPage.js
  client/src/styles/banks-container-grid.scss
Labels: client

#264 Extend Client styling
  client/src/components/Other/BaseCurrencyDropDownList.js
  client/src/components/Other/GroupsContainerComponent.js
  client/src/components/Other/RecentTransactionsContainerComponent.js
  client/src/components/Pages/DashboardPage.js
  client/src/styles/dashboard.scss
Labels: enhancement, client

#266 Improved styling for add new source
  client/src/components/Other/AddNewSourceComponent.js
  client/src/components/Other/AddNewSourceMenu.js
  client/src/components/Other/AddNewSourceModal.js
  client/src/components/Other/BanksContainer.js
  client/src/components/Pages/DashboardPage.js
  client/src/styles/add-source-menu.scss
  client/src/styles/add-source-modal.scss
  client/src/styles/banks-container-grid.scss
  client/src/styles/main_content.scss
Labels: client

#269 Improve Dashboard styling
  client/src/components/Other/AddYodleeComponent.js
  client/src/components/Other/BaseCurrencyDropDownList.js
  client/src/components/Other/GroupsContainerComponent.js
  client/src/components/Other/RecentTransactionsContainerComponent.js
  client/src/styles/dashboard.scss
  client/src/utils/portfolio.js
  server/portfolio/portfolio/utils/reference.py
Labels: enhancement, client

#270 Improved styling for add new source part 2
  client/package.json
  client/src/components/Other/AddNewSourceComponent.js
  client/src/components/Other/AddNewSourceMenu.js
  client/src/components/Pages/DashboardPage.js
  client/src/styles/add-source-menu.scss
  client/src/styles/add-source-modal.scss
  client/src/styles/banks-container-grid.scss
  client/src/styles/dashboard.scss
  client/src/styles/main_content.scss
Labels: client
